---
# vars file for compliance
# IOS-XE Compliance
#SNMP    
snmp_ios:
  groups:
  - group: V3GROUP
    version: v3
    version_option: auth
    read: V3READ  
    write: V3WRITE 
  hosts:   
  - community_string: V3USER
    host: "1.1.1.1"
    version: 3
    version_option: auth
  users:
  - group: V3GROUP
    username: V3USER
    version: v3
    authentication:
      password: snmpauthpass
      algorithm: sha
    encryption:
      password: snmpprevpass
      priv: aes
      priv_option: 256