---
- name: Detect Configuration Changes with kafka as source
  hosts: localhost
  sources:
  - ansible.eda.kafka:
        topic: telegraf
        host: ip-172-16-213-105.us-east-2.compute.internal
        port: 9092
        group_id:
  rules:
    - name: When Config Drifts Run Playbook
      condition: event.body.name == "Cisco-IOS-XE-native:native"
      action:
        run_job_template:
          name: "EDA-Config-Check"
          organization: "Default"
          job_args:
            extra_vars:
              config: "{{ event.body.name}}"
              _group: "{{ event.body.tags.source }}"



