---
- name: Detect Configuration Changes with kafka as source
  hosts: localhost
  sources:
  - ansible.eda.kafka:
        topic: telegraf
        host: ip-172-16-213-105.us-east-2.compute.internal
        port: 9092
        group_id:
  rules:
    - name: When Config Drifts Run Playbook
      condition: event.body.name == "Cisco-IOS-XE-native:native"
      action:
        debug:
          msg: "Config Changed"

   # - name: Retrieve Data and Launch Job-template
   #   condition: events.body.fields.new_state == "interface-notif-state-down" and events.body.fields.if_name in vars.protected
   #   action:
   #     run_job_template:
   #       name: "EDA-Fix-Ports"
   #       organization: "Default"
   #       job_args:
   #         extra_vars:
   #           interface: "{{ event.body.fields.if_name }}"
   #           rtr: "{{ event.body.fields.host_name }}"

