---
# vars file for compliance
# IOS-XE Compliance
#Logging
logging_ios:
  buffered:
    severity: notifications
    size: 12000
  console:
    severity: critical
  facility: local5
  hosts:
  - hostname: 1.1.1.2
  - hostname: 1.1.1.3
  monitor:
    severity: warnings
  snmp_trap:
  - errors
  trap: errors
  userinfo: True