---
- name: Triage Down Interfaces 
  hosts: "{{ _group }}"
  gather_facts: False
  tasks:
  - name: Print
    debug:
     msg: 
      - "{{ config }}"

  - name: Set tag for Compliance Check
    set_fact: 
     tags: snmp
    #when: "'test' in config" 
    when: config.'snmp_server/Cisco_IOS_XE_snmp:community_config/name'.exists

  - name: Print
    debug:
     msg: 
      - "{{ tags }}"
