---
- name: Examine Configuration Changes For Compliance 
  hosts: "{{ _group }}"
  gather_facts: False
  tasks:
  
  - name: Grab Current Time
    set_fact: current_time="{{ lookup('pipe','date +%Y-%m-%d\ %H:%M:%S') }}"

  - name: set_fact when snmp in key
    ansible.builtin.set_fact:
      tag: snmp
    loop: "{{ config | ansible.builtin.dict2items }}"
    when: "'snmp' in item.key"

  - name: set_fact when log in key
    ansible.builtin.set_fact:
      tag: logging
    loop: "{{ config | ansible.builtin.dict2items }}"
    when: "'logging' in item.key"

  - name: set_fact when ntp in key
    ansible.builtin.set_fact:
      tag: ntp
    loop: "{{ config | ansible.builtin.dict2items }}"
    when: "'ntp' in item.key"

  - name: set_fact when ntp in key
    ansible.builtin.set_fact:
      tag: ios-stig
    loop: "{{ config | ansible.builtin.dict2items }}"
    when: "'service' in item.key"

  - name: Run Compliance Roles
    ansible.builtin.include_role:
        name: "../roles/{{ tag | default ('other') }}"

  handlers:
    - name: NTP compliance violation
      ansible.builtin.debug:
        msg:
          - "NTP config compliance violation on {{ inventory_hostname }}"

    - name: Logging compliance violation
      ansible.builtin.debug:
        msg:
          - "Logging compliance violation on {{ inventory_hostname }}"

    - name: SNMP compliance violation
      ansible.builtin.debug:
        msg:
          - "SNMP compliance violation on {{ inventory_hostname }}"
