---
- name: Triage Down Interfaces 
  hosts: "{{ _group }}"
  gather_facts: False
  tasks:
  - name: Print
    debug:
     var: config 

  - name: Set tag for Compliance Check
    set_fact: 
     tags: snmp
    #when: "'snmp_server' in ['config']" 
    #when: config['snmp_server/Cisco_IOS_XE_snmp:community_config/name'] is defined
    when: "config is match('^snmp.*$')"

  - name: Print
    debug:
     msg: 
      - "{{ tags }}"
