---
- name: Triage Down Interfaces 
  hosts: "{{ _group }}"
  gather_facts: False
  tasks:
  - name: Print
    debug:
     msg: "{{ config.key }}" 
    register: config_out

  - name: Set tag for Compliance Check
    set_fact: 
     tags: config
    #when: "'snmp_server' in ['config']" 
    #when: config['snmp_server/Cisco_IOS_XE_snmp:community_config/name'] is defined
    when: config_out == 'snmp_server'

  - name: Print
    debug:
     msg: 
      - "{{ tags }}"
