---
- name: Triage Down Interfaces 
  hosts: "{{ _group }}"
  gather_facts: False
  tasks:
  - name: Print
    debug:
     msg: "{{ config }}" 
    
  - name: set_fact when snmp in key
    ansible.builtin.set_fact:
      tag: snmp
    loop: "{{ lookup('ansible.builtin.dict', config) }}"
    when: "'snmp' in item.key"

  - name: set_fact when log in key
    ansible.builtin.set_fact:
      tag: logging
    loop: "{{ lookup('ansible.builtin.dict', config) }}"
    when: "'logging' in item.key"

  - name: set_fact when ntp in key
    ansible.builtin.set_fact:
      tag: ntp
    loop: "{{ lookup('ansible.builtin.dict', config) }}"
    when: "'ntp' in item.key"

  - name: Print
    debug:
     msg: 
      - "{{ tag }}"
