---
- name: Triage Down Interfaces 
  hosts: "{{ _group }}"
  gather_facts: False
  tasks:
  - name: Print
    debug:
     msg: 
      - "{{ config }}"

  - name: Set tag for Compliance Check
    set_fact: 
     tags: snmp
    when: "'snmp_server' in config[0]" 

  - name: Print
    debug:
     msg: 
      - "{{ tags }}"
