---
- name: Examine Configuration Changes For Compliance 
  hosts: "{{ _group }}"
  gather_facts: False
  vars: 
   save: no 
   ignore_all_errors: false

  tasks:

  - name: Grab Current Time
    set_fact: current_time="{{ lookup('pipe','date +%Y-%m-%d\ %H:%M:%S') }}"

  - name: set_fact when stig in key
    ansible.builtin.set_fact:
      tag: stig-ios
    loop: "{{ config | ansible.builtin.dict2items }}"
    when: "'ip/Cisco_IOS_XE_http:http/server' or 'service/pad_conf/pad' or 'ip/bootp/server' in item.key"
   
  - name: set_fact when snmp in key
    ansible.builtin.set_fact:
      tag: snmp
    loop: "{{ config | ansible.builtin.dict2items }}"
    when: "'snmp' in item.key"

  - name: set_fact when logging in key
    ansible.builtin.set_fact:
      tag: logging
    loop: "{{ config | ansible.builtin.dict2items }}"
    when: "'logging' in item.key"

  - name: set_fact when ntp in key
    ansible.builtin.set_fact:
      tag: ntp
    loop: "{{ config | ansible.builtin.dict2items }}"
    when: "'ntp' in item.key"

  - name: Run Role for Compliance 
    ansible.builtin.include_role:
        name: "../roles/{{ tag | default ('other') }}"

  handlers:
    - name: NTP compliance violation
      ansible.builtin.debug:
        msg:
          - "NTP config compliance violation on {{ inventory_hostname }}"

    - name: Logging compliance violation
      ansible.builtin.debug:
        msg:
          - "Logging compliance violation on {{ inventory_hostname }}"

    - name: SNMP compliance violation
      ansible.builtin.debug:
        msg:
          - "SNMP compliance violation on {{ inventory_hostname }}"
