---
- name: Triage Down Interfaces 
  hosts: "{{ _group }}"
  gather_facts: False
  tasks:
  - name: Print
    debug:
     msg: "{{ config }}" 
    

    #when: config['snmp_server/Cisco_IOS_XE_snmp:community_config/name'] is defined
  

  - name: set_fact when alice in key
    ansible.builtin.set_fact:
      tags: snmp
    loop: "{{ config }}"
    when: "'snmp' in item.key"

  - name: Print
    debug:
     msg: 
      - "{{ tags }}"
